# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: # Don't trigger on files that are updated by the CI
      - 'README.md'
      - 'hello-javalin/README.md'
      - 'hello-angular/README.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_hello_javalin:
    name: Java CI
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: hello-javalin
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn clean install
    
  build_hello_angular:
    needs: build_hello_javalin
    name: Angular CI
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: hello-angular
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install
    #- name: Lint
    #  run: npm run lint
    #  working-directory: hello-angular
    
    - name: Build
      run: npm run build --if-present
    - name: Unit test
      run: npm run test-headless
      env:
        CI: true
    
